# Generated by Django 6.0.6 on 2026-06-26 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("numero", models.IntegerField(help_text="Número de la región")),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Planta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_comun", models.CharField(max_length=150)),
                ("nombre_cientifico", models.CharField(max_length=150, unique=True)),
                (
                    "ubicacion_especifica",
                    models.TextField(help_text="Detalles del hábitat chileno"),
                ),
                ("descripcion_hoja", models.TextField(blank=True, null=True)),
                ("descripcion_tallo", models.TextField(blank=True, null=True)),
                ("descripcion_flor", models.TextField(blank=True, null=True)),
                (
                    "descripcion_detalle",
                    models.TextField(help_text="Detalles claves de identificación"),
                ),
                (
                    "uso_principal",
                    models.CharField(
                        choices=[
                            ("MED", "Medicinal"),
                            ("COM", "Comestible"),
                            ("VEN", "Venenosa"),
                            ("ORN", "Ornamental"),
                            ("IND", "Industrial/Forestal"),
                        ],
                        default="ORN",
                        max_length=3,
                    ),
                ),
                ("detalles_uso", models.TextField(blank=True, null=True)),
                (
                    "imagen_real",
                    models.ImageField(blank=True, null=True, upload_to="plantas/"),
                ),
                (
                    "perenual_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID de la planta en la API de Perenual",
                        null=True,
                    ),
                ),
                (
                    "riego_frecuencia",
                    models.CharField(
                        blank=True,
                        help_text="Dato obtenido de la API",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "luz_solar",
                    models.CharField(
                        blank=True,
                        help_text="Dato obtenido de la API",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "regiones",
                    models.ManyToManyField(related_name="plantas", to="core.region"),
                ),
            ],
            options={
                "ordering": ["nombre_comun"],
            },
        ),
    ]
